// <auto-generated />
using System;
using ImageManagement_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImageManagement_API.Migrations
{
    [DbContext(typeof(Image_APIContext))]
    [Migration("20250925052921_Update2509")]
    partial class Update2509
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ImageManagement_API.Models.Image", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCover")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHotelImg")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLicenseImage")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRoomImg")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTourAgencyImg")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTourImg")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVehicleAgencyImage")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVehicleImage")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LinkedId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ImageID");

                    b.ToTable("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
