// <auto-generated />
using System;
using FeedbackManagement_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeedbackManagement_API.Migrations
{
    [DbContext(typeof(FeedbackManagement_APIContext))]
    partial class FeedbackManagement_APIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FeedbackManagement_API.Model.Feedbacks", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsReply")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LinkedId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LinkedType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("ReplyId")
                        .HasColumnType("int");

                    b.Property<int?>("ReplyToFeedbackId")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("ReplyToFeedbackId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("FeedbackManagement_API.Model.Feedbacks", b =>
                {
                    b.HasOne("FeedbackManagement_API.Model.Feedbacks", "ReplyTo")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToFeedbackId");

                    b.Navigation("ReplyTo");
                });

            modelBuilder.Entity("FeedbackManagement_API.Model.Feedbacks", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
