// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WishListManagement_API.Data;

#nullable disable

namespace WishListManagement_API.Migrations
{
    [DbContext(typeof(WishListManagement_APIContext))]
    [Migration("20250819140907_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WishListManagement_API.Models.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WishlistId"));

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("HotelId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TourId")
                        .HasColumnType("char(36)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<Guid?>("VehiclesId")
                        .HasColumnType("char(36)");

                    b.HasKey("WishlistId");

                    b.ToTable("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
